services:
  primary:
    build: ./postgres-primary
    container_name: pg_primary
    hostname: pg_primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - primary-data:/var/lib/postgresql/data
      - ./scripts:/scripts
    networks:
      - repl_net

  sync:
    build: ./postgres-secondary
    container_name: pg_sync
    hostname: pg_sync
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - primary
    volumes:
      - sync-data:/var/lib/postgresql/data
      - ./scripts:/scripts
    networks:
      - repl_net

  async:
    build: ./postgres-secondary
    container_name: pg_async
    hostname: pg_async
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - primary
    volumes:
      - async-data:/var/lib/postgresql/data
      - ./scripts:/scripts
    networks:
      - repl_net

  pgpool:
    image: bitnami/pgpool:4
    container_name: pgpool
    environment:
      PGPOOL_BACKEND_NODES: "0:pg_primary:5432,1:pg_sync:5432,2:pg_async:5432"
      PGPOOL_SR_CHECK_PERIOD: 10
      PGPOOL_SR_CHECK_USER: postgres
      PGPOOL_POSTGRES_USERNAME: postgres
      PGPOOL_POSTGRES_PASSWORD: password
      PGPOOL_ADMIN_USERNAME: postgres
      PGPOOL_ADMIN_PASSWORD: password
    ports:
      - "9999:9999"
    depends_on:
      - primary
      - sync
      - async
    networks:
      - repl_net

  psql:
    image: postgres:14
    container_name: pg_client
    environment:
      PGPASSWORD: password
    depends_on:
      - pgpool
    networks:
      - repl_net

volumes:
  primary-data:
  sync-data:
  async-data:

networks:
  repl_net:
    driver: bridge
